name: Deploy-website

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install nodejs env
      uses: actions/setup-node@v2.5.2
      with:
        node-version: "18.x"
    - name: install pnpm
      run: npm install -g pnpm
    - name: install deps
      run: pnpm install
    - name: build app
      run: pnpm run build
    - name: copy dist with scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}
        source: "dist/"
        target: ${{ secrets.REMOTE_TARGET }}
    - name: create backup
      run: |
          timestamp=$(date +%s.%N | cut -d '.' -f 1)
          tar czf "backup_${timestamp}.tar.gz" *
          sudo find . -name "backup_*.tar.gz" -mtime +6 -exec rm {} \;
